### PR TITLE
Added a document on how bitmaps are constructed

### PR DESCRIPTION
**Pull request by pcarver**
This adds a file capturing the info in the following post:
https://github.com/pimoroni/dot3k/issues/18#issuecomment-243506754

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Great stuff! I think a few of the points could be explained in a little more depth, plus an example of how to use the finished animation or char maps on the Display-o-Tron, but as a starting point it's extremely illuminating. Thank you!

**Comment by AndiCui** [comment]
I put this in the issue pane. 

Pasting here to get some attention

> 
> @pcarver Nice work!
> One tiny thing for @Gadgetoid to think though
> I prefer this style of binary number, since it is a bit less clunky.
> ```python
> [0b00000,
> # ...
> ]
> ```
> @Gadgetoid What do you think the style in doc should be?

**Comment by pcarver** [comment]
@AndiCui it already got my attention, I just didn't respond because I haven't had any time to work on it. I like the 0b style, so I'm going to update the document I created to show it that way and also see if I can add a little more detail on how to use them. But it's not going to be until at least the weekend.

**Comment by AndiCui** [comment]
Sorry for being verbose. It is more ‘bout poking @Gadgetoid than disturbing you. xD
I already made a pull req https://github.com/pimoroni/dot3k/pull/44. I will already change the style of those integers.
Further information on the usage would be helpful for everyone

Regards
Andi

**Pull request merged**
